services:
  - type: web
    name: trippilot-backend
    runtime: python
    plan: free
    rootDir: backend

    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --settings=config.settings.production
      python manage.py collectstatic --noinput --settings=config.settings.production

    startCommand: gunicorn config.wsgi:application

    envVars:
      - key: PYTHON_VERSION
        value: 3.14.5

      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production