# Generated by Django 6.0.7 on 2026-08-04 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travel', '0003_airport'),
        ('trips', '0004_activity_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(max_length=5, unique=True)),
                ('logo', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_type', models.CharField(choices=[('OUTBOUND', 'Outbound'), ('RETURN', 'Return')], max_length=20)),
                ('flight_number', models.CharField(max_length=20)),
                ('departure_datetime', models.DateTimeField()),
                ('arrival_datetime', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('cabin_class', models.CharField(choices=[('ECONOMY', 'Economy'), ('PREMIUM_ECONOMY', 'Premium Economy'), ('BUSINESS', 'Business'), ('FIRST', 'First')], default='ECONOMY', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stops', models.PositiveIntegerField(default=0)),
                ('baggage_allowance', models.CharField(blank=True, max_length=100)),
                ('refundable', models.BooleanField(default=False)),
                ('aircraft', models.CharField(blank=True, max_length=100)),
                ('terminal', models.CharField(blank=True, max_length=30)),
                ('gate', models.CharField(blank=True, max_length=20)),
                ('booking_reference', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('DELAYED', 'Delayed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flights', to='flights.airline')),
                ('destination_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrival_flights', to='travel.airport')),
                ('source_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departure_flights', to='travel.airport')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='trips.trip')),
            ],
            options={
                'ordering': ['departure_datetime'],
            },
        ),
    ]
