# Generated by Django 6.0.7 on 2026-08-07 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
        ('trips', '0010_layovertrip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='trips.trip'),
        ),
    ]
