# Generated by Django 6.0.7 on 2026-08-07 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_alter_flight_trip'),
        ('travel', '0006_alter_airport_icao_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.PositiveIntegerField()),
                ('is_domestic', models.BooleanField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_routes', to='travel.airport')),
                ('source_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_routes', to='travel.airport')),
            ],
            options={
                'unique_together': {('source_airport', 'destination_airport')},
            },
        ),
    ]
