# Generated by Django 6.0.7 on 2026-08-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_flightroute'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='airline_type',
            field=models.CharField(default='Full Service', max_length=30),
        ),
        migrations.AddField(
            model_name='airline',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='airline',
            name='hub_airport',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='airline',
            name='icao_code',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='airline',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
