# Generated by Django 6.0.7 on 2026-08-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_airline_airline_type_airline_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airline',
            old_name='hub_airport',
            new_name='hub',
        ),
        migrations.RemoveField(
            model_name='airline',
            name='icao_code',
        ),
        migrations.RemoveField(
            model_name='airline',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='airline',
            name='airline_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='airline',
            name='country',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
