# Generated by Django 6.0.7 on 2026-08-06 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_airport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LayoverTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_airport', models.CharField(max_length=10)),
                ('layover_airport', models.CharField(max_length=10)),
                ('destination_airport', models.CharField(max_length=10)),
                ('arrival_date', models.DateField()),
                ('arrival_time', models.TimeField()),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('travel_style', models.CharField(max_length=30)),
                ('ai_result', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layover_trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
