# Generated by Django 6.0.7 on 2026-08-06 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_layovertrip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LayoverTrip',
        ),
    ]
