# Generated by Django 6.0.7 on 2026-08-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_delete_layovertrip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='icao_code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
    ]
