from datetime import time, timedelta

from django.db import transaction

from .models import Activity, ItineraryDay


def parse_time(value):
    """
    Convert AI time string like '09:30'
    into Python time object.
    """

    if not value:
        return time(9, 0)

    try:
        hour, minute = value.split(":")
        return time(int(hour), int(minute))
    except Exception:
        return time(9, 0)


@transaction.atomic
def save_ai_itinerary(
    trip,
    itinerary_days,
):
    """
    Replace the existing itinerary with
    AI generated itinerary.
    """

    # Delete previous itinerary
    trip.days.all().delete()

    for day_data in itinerary_days:
        day_number = day_data["day"]

        itinerary_day = ItineraryDay.objects.create(
            trip=trip,
            day_number=day_number,
            date=trip.departure_date + timedelta(days=day_number - 1),
            title=f"Day {day_number}",
            notes="Generated by AI",
        )

        for activity in day_data.get("activities", []):

            Activity.objects.create(
    itinerary_day=itinerary_day,

    title=activity.get("title", ""),

    location=activity.get("location", ""),

    start_time=parse_time(
        activity.get("time")
    ),

    estimated_cost=activity.get(
        "estimated_cost",
        0,
    ),

    category=activity.get(
        "category",
        "ACTIVITIES",
    ),

    priority=activity.get(
        "priority",
        "MEDIUM",
    ),

    notes=activity.get(
        "description",
        "",
    ),
)