from datetime import datetime, timedelta, time

from django.db import transaction

from apps.flights.models import Airline, Flight
from apps.hotels.models import Hotel
from apps.travel.models import Airport
from apps.trips.models import (
    Activity,
    ItineraryDay,
    Trip,
)


# ==========================================================
# HELPERS
# ==========================================================


def parse_duration_minutes(duration):
    """
    Convert a duration string such as:

        2h 30m
        2h
        45m

    into total minutes.
    """

    if duration is None:
        return 0

    # Already numeric
    if isinstance(
        duration,
        (int, float),
    ):
        return int(duration)

    duration = str(
        duration
    ).strip().lower()

    hours = 0
    minutes = 0

    # ------------------------------------------------------
    # HOURS
    # ------------------------------------------------------

    if "h" in duration:

        hours_part = (
            duration
            .split("h")[0]
            .strip()
        )

        if hours_part:
            hours = int(
                hours_part
            )

    # ------------------------------------------------------
    # MINUTES
    # ------------------------------------------------------

    if "m" in duration:

        if "h" in duration:

            minutes_part = (
                duration
                .split("h", 1)[1]
                .replace("m", "")
                .strip()
            )

        else:

            minutes_part = (
                duration
                .replace("m", "")
                .strip()
            )

        if minutes_part:
            minutes = int(
                minutes_part
            )

    return (
        hours * 60
        + minutes
    )


def parse_datetime(value):
    """
    Parse an ISO datetime generated by FlightGenerator.

    Example:

        2026-08-20T08:30:00+05:30
    """

    if isinstance(
        value,
        datetime,
    ):
        return value

    return datetime.fromisoformat(
        str(value)
    )


# ==========================================================
# CREATE FLIGHT
# ==========================================================


def create_flight(
    *,
    trip,
    flight_data,
    flight_type,
    default_source_airport,
    default_destination_airport,
    default_cabin_class,
):
    """
    Create one Flight database record.

    flight_data is expected to come from:

        ai_trip["flight"]["outbound"]

    or:

        ai_trip["flight"]["return"]
    """

    if not flight_data:
        return None

    # ------------------------------------------------------
    # AIRPORTS
    # ------------------------------------------------------

    source_iata = (
        flight_data.get(
            "source_airport"
        )
        or flight_data.get(
            "departure_airport"
        )
        or default_source_airport.iata_code
    )

    destination_iata = (
        flight_data.get(
            "destination_airport"
        )
        or flight_data.get(
            "arrival_airport"
        )
        or default_destination_airport.iata_code
    )

    source_airport = Airport.objects.get(
        iata_code__iexact=source_iata
    )

    destination_airport = Airport.objects.get(
        iata_code__iexact=destination_iata
    )

    # ------------------------------------------------------
    # AIRLINE
    # ------------------------------------------------------

    airline_code = flight_data.get(
        "airline_code"
    )

    if not airline_code:
        raise ValueError(
            "Flight data is missing airline_code."
        )

    airline = Airline.objects.get(
        code=airline_code
    )

    # ------------------------------------------------------
    # CABIN CLASS
    # ------------------------------------------------------

    cabin_class = (
        flight_data.get(
            "cabin_class"
        )
        or default_cabin_class
    )

    # ------------------------------------------------------
    # DEPARTURE / ARRIVAL
    # ------------------------------------------------------

    departure_datetime = parse_datetime(
        flight_data["departure_time"]
    )

    arrival_datetime = parse_datetime(
        flight_data["arrival_time"]
    )

    # ------------------------------------------------------
    # DURATION
    # ------------------------------------------------------

    duration_minutes = (
        flight_data.get(
            "duration_minutes"
        )
    )

    if duration_minutes is None:

        duration_minutes = (
            parse_duration_minutes(
                flight_data.get(
                    "duration"
                )
            )
        )

    # ------------------------------------------------------
    # CREATE FLIGHT
    # ------------------------------------------------------

    flight = Flight.objects.create(

        trip=trip,

        airline=airline,

        flight_type=flight_type,

        flight_number=flight_data.get(
            "flight_number",
            "",
        ),

        source_airport=source_airport,

        destination_airport=destination_airport,

        departure_datetime=departure_datetime,

        arrival_datetime=arrival_datetime,

        duration_minutes=int(
            duration_minutes
        ),

        cabin_class=cabin_class,

        price=flight_data.get(
            "price",
            0,
        ),

        stops=flight_data.get(
            "stops",
            0,
        ),

        baggage_allowance=(
            flight_data.get(
                "baggage"
            )
            or flight_data.get(
                "baggage_allowance"
            )
            or ""
        ),

        refundable=False,

        aircraft=flight_data.get(
            "aircraft",
            "",
        ),

        terminal=(
            flight_data.get(
                "departure_terminal"
            )
            or ""
        ),

        gate="",

        booking_reference="",
    )

    return flight


# ==========================================================
# SAVE GENERATED TRIP
# ==========================================================


@transaction.atomic
def save_generated_trip(
    *,
    user,
    planner,
    ai_trip,
):
    """
    Save an AI-generated trip.

    Saves:

    - Trip
    - Outbound Flight
    - Return Flight, if available
    - Hotel
    - Itinerary Days
    - Activities

    The generated flight structure is:

        ai_trip["flight"] = {
            "outbound": {...},
            "return": {...},
            "total_price": ...,
            "reason": ...
        }
    """

    # ==========================================================
    # DEBUG
    # ==========================================================

    print("=" * 60)
    print("SAVING GENERATED TRIP")
    print("=" * 60)

    print(
        "SOURCE:",
        repr(
            planner.get(
                "source_airport"
            )
        ),
    )

    print(
        "DESTINATION:",
        repr(
            planner.get(
                "destination_airport"
            )
        ),
    )

    print(
        "DEPARTURE DATE:",
        repr(
            planner.get(
                "departure_date"
            )
        ),
    )

    print(
        "RETURN DATE:",
        repr(
            planner.get(
                "return_date"
            )
        ),
    )

    print("=" * 60)

    # ==========================================================
    # AIRPORTS
    # ==========================================================

    source_airport = Airport.objects.get(
        iata_code__iexact=(
            planner["source_airport"]
        )
    )

    destination_airport = Airport.objects.get(
        iata_code__iexact=(
            planner["destination_airport"]
        )
    )

    # ==========================================================
    # TRIP
    # ==========================================================

    trip = Trip.objects.create(

        user=user,

        source_airport=source_airport,

        destination_airport=destination_airport,

        departure_date=(
            planner["departure_date"]
        ),

        return_date=(
            planner.get(
                "return_date"
            )
        ),

        budget=(
            planner["budget"]
        ),

        adults=(
            planner["adults"]
        ),

        children=(
            planner["children"]
        ),

        infants=(
            planner["infants"]
        ),

        seniors=(
            planner["seniors"]
        ),

        cabin_class=(
            planner["cabin_class"]
        ),

        title=(
            ai_trip[
                "trip_summary"
            ][
                "title"
            ]
        ),

        overview=(
            ai_trip[
                "trip_summary"
            ][
                "overview"
            ]
        ),
    )

    # ==========================================================
    # FLIGHT DATA
    # ==========================================================

    flight_data = ai_trip.get(
        "flight"
    )

    if not flight_data:

        raise ValueError(
            "Generated trip does not contain flight data."
        )

    # ==========================================================
    # OUTBOUND FLIGHT
    # ==========================================================

    outbound_data = flight_data.get(
        "outbound"
    )

    if not outbound_data:

        raise ValueError(
            "Generated trip does not contain an outbound flight."
        )

    outbound_flight = create_flight(

        trip=trip,

        flight_data=outbound_data,

        flight_type=(
            Flight.FlightType.OUTBOUND
        ),

        default_source_airport=(
            source_airport
        ),

        default_destination_airport=(
            destination_airport
        ),

        default_cabin_class=(
            planner["cabin_class"]
        ),
    )

    print(
        "OUTBOUND FLIGHT CREATED:",
        outbound_flight.flight_number,
    )

    # ==========================================================
    # RETURN FLIGHT
    # ==========================================================

    return_data = flight_data.get(
        "return"
    )

    return_flight = None

    if return_data:

        return_flight = create_flight(

            trip=trip,

            flight_data=return_data,

            flight_type=(
                Flight.FlightType.RETURN
            ),

            default_source_airport=(
                destination_airport
            ),

            default_destination_airport=(
                source_airport
            ),

            default_cabin_class=(
                planner["cabin_class"]
            ),
        )

        print(
            "RETURN FLIGHT CREATED:",
            return_flight.flight_number,
        )

    else:

        print(
            "NO RETURN FLIGHT."
        )

    # ==========================================================
    # LINK SELECTED FLIGHT
    #
    # The outbound flight is the primary selected flight.
    #
    # Both flights remain attached to:
    #
    # trip.flights.all()
    # ==========================================================

    trip.selected_flight = (
        outbound_flight
    )

    # ==========================================================
    # HOTEL
    # ==========================================================

    hotel_data = ai_trip.get(
        "hotel"
    )

    hotel = None

    if hotel_data:

        # ------------------------------------------------------
        # HOTEL CHECK-IN
        # ------------------------------------------------------

        check_in = datetime.fromisoformat(
            (
                planner[
                    "departure_date"
                ]
                + "T15:00:00"
            )
        )

        # ------------------------------------------------------
        # HOTEL CHECK-OUT
        # ------------------------------------------------------

        return_date = planner.get(
            "return_date"
        )

        if return_date:

            check_out = datetime.fromisoformat(
                return_date
                + "T11:00:00"
            )

        else:

            # One-way trip fallback
            check_out = (
                check_in
                + timedelta(
                    days=1
                )
            )

        # ------------------------------------------------------
        # HOTEL AMENITIES
        # ------------------------------------------------------

        amenities = hotel_data.get(
            "amenities",
            []
        )

        if not isinstance(
            amenities,
            list,
        ):
            amenities = []

        # ------------------------------------------------------
        # HOTEL
        # ------------------------------------------------------

        hotel = Hotel.objects.create(

            trip=trip,

            name=hotel_data.get(
                "name",
                "",
            ),

            image=hotel_data.get(
                "image",
                "",
            ),

            rating=hotel_data.get(
                "rating",
                0,
            ),

            address=hotel_data.get(
                "address",
                "",
            ),

            city=hotel_data.get(
                "city",
                "",
            ),

            country=hotel_data.get(
                "country",
                "",
            ),

            check_in=check_in,

            check_out=check_out,

            room_type=hotel_data.get(
                "room_type",
                "STANDARD",
            ),

            guests=(
                planner.get(
                    "adults",
                    0,
                )
                + planner.get(
                    "children",
                    0,
                )
                + planner.get(
                    "infants",
                    0,
                )
                + planner.get(
                    "seniors",
                    0,
                )
            ),

            rooms=hotel_data.get(
                "rooms",
                1,
            ),

            price=hotel_data.get(
                "total_price",
                0,
            ),

            breakfast_included=(
                "Breakfast"
                in amenities
            ),

            wifi_included=(
                "WiFi"
                in amenities
            ),

            parking_available=(
                "Parking"
                in amenities
            ),

            amenities=",".join(
                str(item)
                for item in amenities
            ),
        )

    # ==========================================================
    # LINK SELECTED HOTEL
    # ==========================================================

    if hotel:

        trip.selected_hotel = hotel

    # ==========================================================
    # SAVE TRIP SELECTIONS
    # ==========================================================

    update_fields = [
        "selected_flight"
    ]

    if hotel:

        update_fields.append(
            "selected_hotel"
        )

    trip.save(
        update_fields=update_fields
    )

    # ==========================================================
    # ITINERARY
    # ==========================================================

    itinerary = ai_trip.get(
        "itinerary",
        []
    )

    departure_date = datetime.fromisoformat(
        planner[
            "departure_date"
        ]
    ).date()

    for day_data in itinerary:

        day_number = int(
            day_data["day"]
        )

        itinerary_day = (
            ItineraryDay.objects.create(

                trip=trip,

                day_number=day_number,

                date=(
                    departure_date
                    + timedelta(
                        days=day_number - 1
                    )
                ),

                title=day_data.get(
                    "title",
                    "",
                ),
            )
        )

        # ------------------------------------------------------
        # ACTIVITIES
        # ------------------------------------------------------

        activities = day_data.get(
            "activities",
            []
        )

        for activity in activities:

            activity_time = datetime.strptime(
                activity["time"],
                "%H:%M",
            ).time()

            Activity.objects.create(

                itinerary_day=(
                    itinerary_day
                ),

                title=activity.get(
                    "title",
                    "",
                ),

                description=activity.get(
                    "description",
                    "",
                ),

                location=activity.get(
                    "location",
                    "",
                ),

                city=activity.get(
                    "city",
                    "",
                ),

                country=activity.get(
                    "country",
                    "",
                ),

                transport=activity.get(
                    "transport",
                    "",
                ),

                start_time=(
                    activity_time
                ),

                end_time=time(
                    activity_time.hour,
                    activity_time.minute,
                ),

                estimated_cost=activity.get(
                    "estimated_cost",
                    0,
                ),

                category=activity.get(
                    "category",
                    Activity.Category.ACTIVITIES,
                ),

                priority=activity.get(
                    "priority",
                    Activity.Priority.MEDIUM,
                ),
            )

    # ==========================================================
    # FINAL DEBUG
    # ==========================================================

    print("=" * 60)
    print("TRIP SAVED SUCCESSFULLY")
    print(
        "TRIP ID:",
        trip.id,
    )
    print(
        "OUTBOUND:",
        outbound_flight.id
        if outbound_flight
        else None,
    )
    print(
        "RETURN:",
        return_flight.id
        if return_flight
        else None,
    )
    print("=" * 60)

    return trip