# Generated by Django 6.0.7 on 2026-08-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('ACCOMMODATION', 'Accommodation'), ('TRANSPORT', 'Transport'), ('FOOD', 'Food'), ('ACTIVITIES', 'Activities'), ('SHOPPING', 'Shopping'), ('ENTERTAINMENT', 'Entertainment'), ('MISCELLANEOUS', 'Miscellaneous')], default='ACTIVITIES', max_length=30),
        ),
    ]
