# Generated by Django 6.0.7 on 2026-08-05 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
        ('trips', '0004_activity_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='selected_flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_for_trips', to='flights.flight'),
        ),
    ]
