# Generated by Django 6.0.7 on 2026-08-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_trip_selected_hotel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='travelers',
            new_name='adults',
        ),
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='infants',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='seniors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
