# Generated by Django 6.0.7 on 2026-08-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_rename_travelers_trip_adults_activity_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='activity',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='activity',
            name='transport',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
