# Generated by Django 6.0.7 on 2026-08-05 18:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
        ('hotels', '0001_initial'),
        ('travel', '0003_airport'),
        ('trips', '0008_activity_city_activity_country_activity_transport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['category'], name='trips_activ_categor_578796_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['priority'], name='trips_activ_priorit_333456_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['user'], name='trips_trip_user_id_b0cf72_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['status'], name='trips_trip_status_259ca6_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['departure_date'], name='trips_trip_departu_7bc4b1_idx'),
        ),
    ]
